# Generated by Django 4.0.2 on 2022-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
