# Generated by Django 4.0.2 on 2022-02-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(choices=[('Consert', 'Concert'), ('Cinema', 'Cinema'), ('Theater', 'Theater'), ('Other', 'Other')], max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('OS', 'Oslo'), ('BR', 'Bergen'), ('TR', 'Trondheim'), ('BO', 'Bodø')], max_length=50),
        ),
    ]
