# Generated by Django 4.0.2 on 2022-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_description_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Consert', 'Concert'), ('Cinema', 'Cinema'), ('Theater', 'Theater'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
