# Generated by Django 4.0.2 on 2022-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_saleorbuy_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contactInfo',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Consert', 'Consert'), ('Cinema', 'Cinema'), ('Theater', 'Theater'), ('Other', 'Other')], max_length=50),
        ),
    ]
