# Generated by Django 4.0.2 on 2022-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_contactinfo_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contactInfo',
            field=models.CharField(max_length=120),
        ),
    ]
