# Generated by Django 4.0.2 on 2022-03-15 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='rating',
            new_name='buyerRation',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerRating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
