# Generated by Django 4.0.2 on 2022-03-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_post_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flaggedBy',
            field=models.ManyToManyField(related_name='flaggedPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
