# Generated by Django 4.0.2 on 2022-03-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_rating_transaction_buyerration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyerRation',
            new_name='buyerRating',
        ),
    ]
