# Generated by Django 4.0.2 on 2022-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_flaggedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='flaggedBy',
        ),
        migrations.AddField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
