# Generated by Django 4.0.2 on 2022-03-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyerRating',
            new_name='ratingFromBuyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sellerRating',
            new_name='ratingFromSeller',
        ),
    ]
