# Generated by Django 4.0.2 on 2022-03-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_rename_buyerrating_transaction_ratingfrombuyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ratingFromBuyer',
            field=models.PositiveIntegerField(default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ratingFromSeller',
            field=models.PositiveIntegerField(default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
