# Generated by Django 4.0.2 on 2022-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_transaction_ratingfrombuyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ratingFromBuyer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ratingFromSeller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
