# Generated by Django 4.0.2 on 2022-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postOwnerUsername',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
