# Generated by Django 4.0.2 on 2022-03-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_post_postownerusername'),
        ('post', '0019_alter_transaction_buyer'),
    ]

    operations = [
    ]
